Dogs/urls.py

from django.urls import path

from Dogs.views import index

urlpatterns = [
    path('', index)
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dogs.urls', namespace='dog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import IndexView, DogListView, DogCreateView, DogUpdateView, DogDeleteView, \
    BreedDetailView, BreedListView, DogDetailView

app_name = DogsConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('breeds/', BreedListView.as_view(), name='breeds'),
    path('breed/detail/<int:pk>', BreedDetailView.as_view(), name='breed_detail'),

    path('<int:pk>/dogs/', DogListView.as_view(), name='breeds_dogs'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/<int:pk>/update/', DogUpdateView.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/detail/', DogDetailView.as_view(), name='dogs_detail'),
    path('dogs/delete/<int:pk>', DogDeleteView.as_view(), name='dogs_delete'),

]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password

app_name = UsersConfig.name


urlpatterns= [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),

]

dogs/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

NULLABLE = {'blank': True, 'null': True}


class Breed(models.Model):
    name = models.CharField(max_length=150, verbose_name='Порода')
    description = models.TextField(**NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'порода'
        verbose_name_plural = 'породы'


class Dog(models.Model):
    name = models.CharField(max_length=150, verbose_name='Кличка')
    # breed = models.CharField(max_length=150, verbose_name='Порода')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    photo = models.ImageField(upload_to='dogs/', **NULLABLE, verbose_name='Фото')
    birth_day = models.DateTimeField(**NULLABLE, verbose_name='Дата рождения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    #def get_absolute_url(self):
    #    return reverse('dogs:detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.name} {self.breed} {self.photo} {self.birth_day}'

    class Meta:
        verbose_name = 'собака'
        verbose_name_plural = 'собаки'

class Parent(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    birth_day = models.DateTimeField(**NULLABLE, verbose_name='Дата рождения')

    def __str__(self):
        return f'{self.name} {self.breed}:{self.birth_day}'

    class Meta:
        verbose_name = 'предок'
        verbose_name_plural = 'предки'

dogs/forms.py
import datetime

from django import forms

from dogs.models import Dog, Parent


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class DogForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Dog
        #fields = '__all__'
        exclude = ('owner',)

    def clean_birth_day(self):
        cleaned_data = self.cleaned_data['birth_day']
        now_year = datetime.datetime.now().year
        if now_year - cleaned_data.year > 100:
            raise forms.ValidationError('Собака слишком дряхлая')
        return cleaned_data



class ParentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Parent
        fields = '__all__'

Dogs/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        breed = request.POST.get('breed')
        foto = request.POST.get('foto')
        dr = request.POST.get('dr')
        print(f'{name} {breed} {foto} {dr}')
    return render(request, 'Dogs/index.html')

dogs/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, DetailView
from pytils.translit import slugify

from dogs.forms import DogForm, ParentForm
from dogs.models import Breed, Dog, Parent


class IndexView(TemplateView):
    template_name = 'dogs/index.html'
    extra_context = {
        'title': 'Питомник - Главная'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Breed.objects.all()[:3]
        return context_data


class BreedListView(ListView):
    model = Breed
    extra_context = {
        'title': 'Питомник - Все наши породы'
    }


class BreedDetailView(DetailView):
    model = Breed
    success_url = reverse_lazy('dogs:breeds')



class DogListView(ListView):
    model = Dog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(breed_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        breed_item = Breed.objects.get(pk=self.kwargs.get('pk'))
        context_data['breed_pk'] = 'breed_item.pk',
        context_data['title'] = f'Собаки породы - Все наши породы {breed_item.name}'

        return context_data




class DogCreateView(CreateView):
    model = Dog
    form_class = DogForm
    success_url = reverse_lazy('dogs:breeds')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class DogUpdateView(UpdateView):
    model = Dog
    form_class = DogForm

    # success_url = reverse_lazy('dogs:breeds')

    def get_success_url(self):
        return reverse('dogs:dogs_update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ParentFormset = inlineformset_factory(Dog, Parent, form=ParentForm, extra=1)
        if self.request.method == 'POST':
            formset = ParentFormset(self.request.POST, instance=self.object)
        else:
            formset = ParentFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class DogDetailView(DetailView):
    model = Dog




class DogDeleteView(DeleteView):
    model = Dog
    success_url = reverse_lazy('dog:breeds')


"""def index(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        breed = request.POST.get('breed')
        photo = request.POST.get('foto')
        birth_day = request.POST.get('dr')
        print(f'{name} {breed} {photo} {birth_day}')
    return render(request, 'dogs/base.html')"""

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Информация</h4>
                    <p class="text-muted"></p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'dogs:index'  %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'dogs:breeds'  %}" class="text-white">Породы</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:profile'  %}" class="text-white">Профиль</a></li>
                            <li><a href="{% url 'users:logout'  %}" class="text-white">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login'  %}" class="text-white">Войти</a></li>
                            <li><a href="{% url 'users:register'  %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Питомник</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
                <p class="lead text-muted">Будь в курсе</p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}


        </div>
    </div>

</main>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script defer src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

dogs/templates/dogs/breed_detail.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о собаках
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Кличка</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>О породе</td>
                            <td>{{ object.description }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <input type="button" onclick="history.back();" value="Назад" style="margin-top: 10px;"/>
        </div>
    </div>
</div>
{% endblock %}

dogs/templates/dogs/breed_list.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col-12">
        <a href="{% url 'dogs:dog_create'  %}" class="btn btn-primary">Создать собаку</a>
    </div>
    {% for object in object_list %}
    {% include 'dogs/includes/inc_breed.html' %}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/breeds.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
    {% include 'dogs/includes/inc_breed.html' %}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/dog_confirm_delete.html
{% extends 'dogs/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление собаки
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить собаку {{ object.name }}</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-warning-outline" href=" {% url 'dogs:breeds_dogs' object.pk %}">Отмена</a>
            </div>
        </div>
    </div>
</form>


{% endblock %}

dogs/templates/dogs/dog_detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о собаке
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                                <rect width="100%" height="100%" fill="#55595c"/>
                                <image href="{{ object.photo | mymedia }}" width="100%" height="100%"/>
                            </svg>
                        </tr>
                        <tr>
                            <td>Кличка</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>Порода</td>
                            <td>{{ object.breed }}</td>
                        </tr>
                        <tr>
                            <td>О породе</td>
                            <td>{{ object.breed.description }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <input type="button" onclick="history.back();" value="Назад" style="margin-top: 10px;"/>
        </div>
    </div>
</div>
{% endblock %}

dogs/templates/dogs/dog_form.html
{% extends 'dogs/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование собаки
                {% else %}
                Добавление собаки
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Родословная
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if forloop.revcounter0 != 0 %}
                    <hr>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>


{% endblock %}

dogs/templates/dogs/dog_list.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"/>
                <image href="{{ object.photo | mymedia }}" width="100%" height="100%"/>
            </svg>

            <div class="card-body">
                <p class="card-text">{{ object.name|title }}</p>
                <span class="text-muted">{{ object.birth_day }}</span><br>
                <span class="text-muted">{{ object.owner|default:"Без хозяина" }}</span>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="card_footer">
                        <a class="btn btn-outline-success" href="{% url 'dogs:dogs_detail' object.pk %}">Посмотреть</a>
                        <a class="btn btn-outline-success" href="{% url 'dogs:dogs_update' object.pk %}">Изменить</a>
                        <a class="btn btn-outline-danger float-right" href="{% url 'dogs:dogs_delete' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"/>
                <image href="{{ object.photo | mymedia }}" width="100%" height="100%"/>
            </svg>

            <div class="card-body">
                <p class="card-text">{{ object.name|title }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 mins</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
    {% include 'dogs/includes/inc_breed.html' with object=object%}
    {% endfor %}
</div>
{% endblock %}